class   TestFinally
{   
	 
	public static void main(String[] args) 
	{


        try{
		 System.out.println( 1/0);
		} finally{
             System.out.println("ArithmeticException is caught");
		}

	}
}
